[package]
name = "tsl2591_sensor"
version = "0.1.0"
authors = ["Robbie Lamb <lamb@eccentriclamb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"

[dev-dependencies]
simple-signal = "1.1.1"
